const LeaderboardActionTypes = {
  
    SELECT_ROUND_LEADERBOARD_START: 'SELECT_ROUND_LEADERBOARD_START',
    SELECT_ROUND_LEADERBOARD_SUCCESS: 'SELECT_ROUND_LEADERBOARD_SUCCESS',
    SELECT_ROUND_LEADERBOARD_FAILURE: 'SELECT_ROUND_LEADERBOARD_FAILURE',

    SELECT_SEASON_LEADERBOARD_START: 'SELECT_SEASON_LEADERBOARD_START',
    SELECT_SEASON_LEADERBOARD_SUCCESS: 'SELECT_SEASON_LEADERBOARD_SUCCESS',
    SELECT_SEASON_LEADERBOARD_FAILURE: 'SELECT_SEASON_LEADERBOARD_FAILURE',

    SET_SELECTED_ROUND: 'SET_SELECTED_ROUND',
    SET_SELECTED_SEASON: 'SET_SELECTED_SEASON'
};

export default LeaderboardActionTypes;