const SeasonActionTypes = {
    SET_LATEST_SEASON_START: 'SET_LATEST_SEASON_START',
    SET_LATEST_SEASON_SUCCESS: 'SET_LATEST_SEASON_SUCCESS',
    SET_LATEST_SEASON_FAILURE: 'SET_LATEST_SEASON_FAILURE',
};

export default SeasonActionTypes;